version: "3.8"
services:
  app:
    restart: always
    build: .
    container_name: 'site_compare_app'
    working_dir: '/code'
    stdin_open: true
    tty: true
    volumes:
      - ./data:/home/app_user/data