version: "3.8"
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    stdin_open: true
    tty: true
    volumes:
      - ./data:/home/app_user/data