version: "3.8"
services:
  site_compare:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    image: site_compare
    container_name: 'site_compare'
    working_dir: '/home/kenphanith'
    stdin_open: true
    tty: true
    volumes:
      - ./site_compare.py:/home/kenphanith/site_compare.py