version: "3.8"
services:
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        CHROMEDRIVER_DIR: ${CHROMEDRIVER_DIR}
        CHROMEDRIVER_VERSION: ${CHROMEDRIVER_VERSION}
    working_dir: '/code'
    stdin_open: true
    tty: true
    volumes:
      - ./:/code
    networks:
      - site_compare
networks:
  site_compare:
    driver: bridge